// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package admin_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "football-stat-goth/views/layouts"

func Players() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"w-full p-4 bg-primary-background min-h-screen flex flex-col justify-center items-center\"><h1 class=\"font-bold text-3xl text-center mb-4\">Add New Player</h1><form class=\"flex flex-col items-center space-y-2 w-56\" hx-post=\"/api/players\"><input name=\"club_id\" type=\"text\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"Club ID\"> <input name=\"no\" type=\"number\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"No.\"> <input name=\"firstname\" type=\"text\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"First Name\"> <input name=\"lastname\" type=\"text\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"Last Name\"> <label for=\"dob\">Date of Birth</label> <input name=\"dob\" type=\"date\" required class=\"p-1 rounded-md border border-primary w-full\"> <input name=\"height\" type=\"number\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"Height\"> <input name=\"nationality\" type=\"text\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"Nationality\"> <label for=\"position\">Position</label> <select name=\"position\" required class=\"p-1 rounded-md border border-primary w-full\"><option>GK</option> <option>DEF</option> <option>MFD</option> <option>FWD</option> <option>SUB</option></select> <input name=\"image\" type=\"text\" required class=\"p-1 rounded-md border border-primary w-full\" placeholder=\"Image URL\"> <input type=\"submit\" value=\"Submit\" class=\"bg-secondary-background px-4 py-2 rounded-lg hover:bg-secondary-foreground font-bold text-primary-background hover:cursor-pointer transition-colors\"></form></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
