// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: match.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMatchesWithClubsAndGoals = `-- name: ListMatchesWithClubsAndGoals :many
SELECT
    match.id, match.home_lineup_id, match.away_lineup_id, match.season, match.week, match.location, match.start_at, match.is_finished,
    "home_club".id AS home_club_id,
    "home_club".logo AS home_club_logo,
    "home_lineup".goals AS home_goals,
    "away_club".id AS away_club_id,
    "away_club".logo AS away_club_logo,
    "away_lineup".goals AS away_goals
FROM "match"
INNER JOIN "lineup" as home_lineup
ON "match".home_lineup_id = home_lineup.id
INNER JOIN "club" as home_club
ON home_lineup.club_id = home_club.id
INNER JOIN "lineup" as away_lineup
ON "match".away_lineup_id = away_lineup.id
INNER JOIN "club" as away_club
ON away_lineup.club_id = away_club.id
WHERE
    is_finished = $1::bool AND
    CASE WHEN $2::bool
    THEN "home_club".id = $3::text
    ELSE true
    END
ORDER BY
    CASE WHEN $4::text = 'ASC' THEN "match".start_at END ASC,
    CASE WHEN $4::text = 'DESC' THEN "match".start_at END DESC
`

type ListMatchesWithClubsAndGoalsParams struct {
	IsFinished   bool
	FilterClubID bool
	ClubID       string
	Order        string
}

type ListMatchesWithClubsAndGoalsRow struct {
	ID           int32
	HomeLineupID int32
	AwayLineupID int32
	Season       string
	Week         int16
	Location     string
	StartAt      pgtype.Timestamp
	IsFinished   bool
	HomeClubID   string
	HomeClubLogo string
	HomeGoals    int16
	AwayClubID   string
	AwayClubLogo string
	AwayGoals    int16
}

func (q *Queries) ListMatchesWithClubsAndGoals(ctx context.Context, arg ListMatchesWithClubsAndGoalsParams) ([]ListMatchesWithClubsAndGoalsRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithClubsAndGoals,
		arg.IsFinished,
		arg.FilterClubID,
		arg.ClubID,
		arg.Order,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesWithClubsAndGoalsRow
	for rows.Next() {
		var i ListMatchesWithClubsAndGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeLineupID,
			&i.AwayLineupID,
			&i.Season,
			&i.Week,
			&i.Location,
			&i.StartAt,
			&i.IsFinished,
			&i.HomeClubID,
			&i.HomeClubLogo,
			&i.HomeGoals,
			&i.AwayClubID,
			&i.AwayClubLogo,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
